### ISSUE TITLE
Negative Ping?

### ISSUE THREAD

**Issue by iLexy3** [meew0/discord-bot-best-practices#40]
So I have this code for my bot that shows how long it takes to respond and it keeps showing a negative value like this: 

Bot ping: -1214ms
Api ping: 39ms

Here's the code:

bot.on("message", async (message) => {
    if (message.author.bot) return;
    let prefix = config.prefix

    let args = message.content.slice(prefix.length).trim().split(/ +/)
    let cmd = args.shift().toLowerCase()

    if(cmd==="ping") {
        let botping = new Date() - message.createdAt
        let apiping = bot.ping

        return message.channel.send(`Bot ping: ${botping}ms\nApi ping: ${apiping}ms`)
    }
})

bot.login(config.token)

...So how do I fix it? I'm new at this so please go easy on me. :)

**Comment by FireController1847** [comment]
Once again, this is not the place to ask. If you're using Discord.js (which it appears you are), please ask in their Discord server @ https://discord.gg/bRCvFy9

**Comment by Jeydin21** [comment]
Hey, I know it's been a long time, but actually you have to flip new Date() and message.createdAt around, your ping is actually 1214ms, but because it's opposite, it's negative

**Comment by binary-person** [comment]
Came across this while searching why `msg.createdAt` is somehow greater than current time.

for anyone who saw the previous msgs, you should do `Date.now()` instead of `new Date()`. also, you do not flip Date and msg.createdAt around because we want to do `now - oldTime`, not `oldTime - now`. `oldTime` in a perfect clocked synced world will always be less than `now`.

If `Date.now() - msg.createdAt` is negative, that would mean `msg.createdAt` > `Date.now()`. I would guess the issue would be that the clock of the machine running the discord bot is behind discord's clock.
